In [1]:
# 아나콘다 가상환경이니까, 설치 안 되어 있을 수 있으니 설치 시도

!pip install matplotlib
!pip install wordcloud

Requirement already satisfied: matplotlib in C:\Users\HP\anaconda3\Lib\site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.25 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\HP\anaconda3\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Collecting wordcloud
  Downloading wordcloud-1.9.6-cp314-cp314-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.19.3 in C:\Users\HP\anaconda3\Lib\site-packages (from wordcloud) (2.4.6)
Requirement already satisfied: pillow in C:\Users\HP\anaconda3\Lib\site-packages (from wordcloud) (12.3.0)
Requirement already satisfied: matplotlib in C:\Users\HP\anaconda3\Lib\site-packages (from wordcloud) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib->wordcloud) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib->wordcloud) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib->wordcloud) (26.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib->wordcloud) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\HP\anaconda3\Lib\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\HP\anaconda3\Lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)
Downloading wordcloud-1.9.6-cp314-cp314-win_amd64.whl (308 kB)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.9.6

In [2]:
import pandas as pd
import glob # 윈도우 디렉터리 관련
import re # Regular Expression(정규표현식). 정제 관련
from functools import reduce
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords # 불용어 단어셋
from nltk.stem import WordNetLemmatizer # 표제어 추출
from collections import Counter # 단어 안 겹치게. 얼마나 나왔는지 빈도수 체크.
import matplotlib.pyplot as plt
from wordcloud import STOPWORDS, WordCloud

In [3]:
all_files = glob.glob('ch08_data/exportExcelData_*.xls')
all_files

['ch08_data\\exportExcelData_20261027150515.xls',
 'ch08_data\\exportExcelData_20261027150539.xls',
 'ch08_data\\exportExcelData_20261027150558.xls',
 'ch08_data\\exportExcelData_20261027150621.xls',
 'ch08_data\\exportExcelData_20261027162459.xls',
 'ch08_data\\exportExcelData_20261027162535.xls',
 'ch08_data\\exportExcelData_20261027162601.xls',
 'ch08_data\\exportExcelData_20261027162624.xls',
 'ch08_data\\exportExcelData_20261027162647.xls',
 'ch08_data\\exportExcelData_20261027162713.xls']

In [5]:
# No module named 'xlrd' 에러를 해결하기 위해 xlrd 라이브러리 설치
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [6]:
all_files_data = [] # 저장할 리스트
for file in all_files:
    data_frame = pd.read_excel(file)
    all_files_data.append(data_frame)
all_files_data[0]

,Unnamed: 0,번호,제목,저자,출판사,출판일
0,NaN,1,Model my watershed: an investigation into the ...,"Marcum-Dietrich, Nanette; Kerlin, Steve; Hendr...",Taylor & Francis,2021
1,NaN,2,Architecting Time-Critical Big-Data Systems,"Basanta-Val, P.; Audsley, N. C.; Wellings, A. ...",unknown,2016
2,NaN,3,A Game Theoretic Approach for Addressing Domai...,"Raghavan, Krishnan",unknown,2022
3,NaN,4,Computation migration: a new approach to execu...,"Nunes, Rickey T. P.; Deshpande, Santosh L.",Inderscience,2018
4,NaN,5,A trust-based crowdfunding campaign marketing ...,"Baah-Peprah, Prince; Shneor, Rotem",Inderscience,2021
...,...,...,...,...,...,...
95,NaN,96,Big Data As an Enabler of Primary Education,unknown,Mary Ann Leibert,2016
96,NaN,97,Unsupervised Tensor Mining for Big Data Practi...,unknown,Mary Ann Leibert,2016
97,NaN,98,Attribute-Based Adaptive Homomorphic Encryptio...,"THENMOZHI, R.;SHRIDEVI, S.;MOHANTY, S. N.;GARC...",Mary Ann Liebert,2024
98,NaN,99,Towards Efficient Energy Utilization Using Big...,"Arif, Arooj","Elsevier Science B.V., Amsterdam",2022
99,NaN,100,A Weighted GraphSAGE-Based Context-Aware Appro...,"SHAN, D.;DU, X.;WANG, W.;LIU, A.WANG, N.",Mary Ann Liebert,2024

In [7]:
all_files_data_concat = pd.concat(all_files_data, axis = 0, ignore_index = True)
all_files_data_concat

,Unnamed: 0,번호,제목,저자,출판사,출판일
0,NaN,1,Model my watershed: an investigation into the ...,"Marcum-Dietrich, Nanette; Kerlin, Steve; Hendr...",Taylor & Francis,2021
1,NaN,2,Architecting Time-Critical Big-Data Systems,"Basanta-Val, P.; Audsley, N. C.; Wellings, A. ...",unknown,2016
2,NaN,3,A Game Theoretic Approach for Addressing Domai...,"Raghavan, Krishnan",unknown,2022
3,NaN,4,Computation migration: a new approach to execu...,"Nunes, Rickey T. P.; Deshpande, Santosh L.",Inderscience,2018
4,NaN,5,A trust-based crowdfunding campaign marketing ...,"Baah-Peprah, Prince; Shneor, Rotem",Inderscience,2021
...,...,...,...,...,...,...
995,NaN,96,Big data's dark side,unknown,Institution of Engineering and Technology,2016
996,NaN,97,Big Data: The New Information Challenge,"Arnold, S.E.",ONLINE INC,2011
997,NaN,98,"Big data: the elements of good questions, open...","Ho, Joshua W. K.; Giannoulatou, Eleni",SPRINGER,2019
998,NaN,99,Big Data in product lifecycle management,"Li, J.; Tao, F.; Cheng, Y.; Zhao, L.",Springer Science + Business Media,2015
999,NaN,100,Big Data-Oriented Product Infant Failure Intel...,unknown,IEEE,2019

In [13]:
all_files_data_concat.to_csv('ch08_data/riss_bigdata.csv', encoding = 'utf-8-sig', index = False) # 컬럼명이 한글이므로, 깨지지 안cp949로 설정